// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvOkx3bvkwGaIq9rVbU-J8y8Uopi-1jg',
    appId: '1:286463155652:android:04e2213011fee179ad9891',
    messagingSenderId: '286463155652',
    projectId: 'circular-words-dev',
    storageBucket: 'circular-words-dev.firebasestorage.app',
  );

  // Added from ios/flavors/dev/GoogleService-Info.plist: the FlutterFire
  // CLI's iOS step needs Ruby's xcodeproj gem and rewrites the Xcode project,
  // neither of which this app wants — it initialises Firebase from Dart.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCih-Ox7LpZKWcq0KAZxRreahhNJe2-O8Y',
    appId: '1:286463155652:ios:9102ba3400b20832ad9891',
    messagingSenderId: '286463155652',
    projectId: 'circular-words-dev',
    storageBucket: 'circular-words-dev.firebasestorage.app',
    iosBundleId: 'com.yusubov.circularwords.dev',
  );
}
