// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzj1uaAfbvPgFz7ui27fZ8hZDThMg2qLM',
    appId: '1:1030077587671:android:ea86e01f5215d565dc9092',
    messagingSenderId: '1030077587671',
    projectId: 'circular-words-prod',
    storageBucket: 'circular-words-prod.firebasestorage.app',
  );

  // Added from ios/flavors/prod/GoogleService-Info.plist: the FlutterFire
  // CLI's iOS step needs Ruby's xcodeproj gem and rewrites the Xcode project,
  // neither of which this app wants — it initialises Firebase from Dart.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8uiXbDr6qXJNpmrdoLYNjzz74OvSYW-E',
    appId: '1:1030077587671:ios:0850d10d52a9036edc9092',
    messagingSenderId: '1030077587671',
    projectId: 'circular-words-prod',
    storageBucket: 'circular-words-prod.firebasestorage.app',
    iosBundleId: 'com.yusubov.circularwords',
  );
}
