name: rosco_impl
description: "Implementation details of the Rosco feature"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  rosco_api:
  analytics_api:
  dependency_injection_api:
  router_api:
  design_system:
  feedback_api:
  speech_api:
  state_manager:
  app_localization:
  storage_api:
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/words/
