name: rosco_impl
description: "Implementation details of the Rosco feature"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  rosco_api:
  dependency_injection_api:
    git:
      url: https://github.com/Yusubov-Engineering/dependency_injection.git
      path: dependency_injection_api
      ref: v1.0.0
  router_api:
    git:
      url: https://github.com/Yusubov-Engineering/router.git
      path: router_api
      ref: v1.1.0
  design_system:
  feedback_api:
  speech_api:
    git:
      url: https://github.com/Yusubov-Engineering/speech.git
      path: speech_api
      ref: v1.0.0
  state_manager:
    git:
      url: https://github.com/Yusubov-Engineering/state_manager.git
      path: .
      ref: v1.0.0
  app_localization:
  storage_api:
    git:
      url: https://github.com/Yusubov-Engineering/storage.git
      path: storage_api
      ref: v1.0.0
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/words/
