analyzer:
  exclude:
    - build/**
    - "**/build/**"
    - tool/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:app_linter/analysis_options.yaml