name: logger_impl
description: "Implementation details of the Logger Module"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^5.1.20
  material_ui: ^1.0.0 
  talker_dio_logger: 
  dependency_injection_api:
  logger_api:

dev_dependencies:
  app_linter:
