name: feedback_impl
description: "Implementation details of the game feedback module"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  feedback_api:
  audioplayers: ^6.5.1
  dependency_injection_api:
    git:
      url: https://github.com/Yusubov-Engineering/dependency_injection.git
      path: dependency_injection_api
      ref: v1.0.0
  storage_api:
    git:
      url: https://github.com/Yusubov-Engineering/storage.git
      path: storage_api
      ref: v1.0.0

dev_dependencies:
  audioplayers_platform_interface: ^7.2.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sounds/
