// GENERATED BY `modular gen assets` — DO NOT EDIT BY HAND.
// Add or remove files under assets/vectors/ and regenerate.

final class const AppVectorAsset({
  required final String path,
  required final String packageName,
});

abstract class AppVectorAssets {
  static const arrowRight = AppVectorAsset(
    path: 'vectors/arrow-right.svg',
    packageName: 'assets',
  );
}
