// GENERATED BY `modular gen assets` — DO NOT EDIT BY HAND.
// Add or remove files under assets/rasters/ and regenerate.

final class const AppRasterAsset({
  required final String path,
  required final String packageName,
});

abstract class AppRasterAssets {
  static const placeholder = AppRasterAsset(
    path: 'rasters/placeholder.webp',
    packageName: 'assets',
  );
}
