name: levels_impl
description: "Implementation details of the Levels feature"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  levels_api:
  analytics_api:
  dependency_injection_api:
  router_api:
  design_system:
  feedback_api:
  state_manager:
  app_localization:
  rosco_api:

dev_dependencies:
  flutter_test:
    sdk: flutter
