name: app
description: "Composition root: wires every module together"
publish_to: 'none'
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ### CORE MODULES
  analytics_api:
  analytics_impl:
  network_api:
  network_impl:
  router_api:
  router_impl:
  logger_api:
  logger_impl:
  biometric_auth_impl:
  storage_impl:
  dependency_injection_api:
  dependency_injection_impl:
  speech_api:
  speech_impl:
  design_system:
  feedback_impl:

  ### BASE MODULES
  app_localization:
  app_network_contract:

  ### FEATURE MODULES
  levels_impl:
  rosco_impl:

  ### EXTERNAL PACKAGES
  material_ui: ^1.0.0
  flutter_native_splash: ^2.4.8
