name: rosco_api
description: "Api protocols of the Rosco feature"
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  design_system:
  router_api:
